import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./NavBar";
import { ClerkProvider } from "@clerk/nextjs";
import { LevelProvider } from "./context/level-context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Ear Trainer",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkProvider>
            <LevelProvider>
                <html lang="en">
                    <body className={inter.className}>
                        <NavBar />
                        {children}
                    </body>
                </html>
            </LevelProvider>

        </ClerkProvider>

    );
}
