import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./NavBar";
import { LevelProvider } from "./context/levelContext";
import { QuestionProvider } from "@/app/context/questionContext";
import { NumberQuestionProvider } from "./context/numberQuestionsContext";
import { TimeProvider } from "./context/timeContext";
import { validateRequest } from "@/lib/validateRequest";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Ear Trainer",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    const user = await validateRequest();
    return (
        <QuestionProvider>
            <NumberQuestionProvider>
                <LevelProvider>
                    <TimeProvider>
                        <html lang="en">
                            <body className={inter.className}>
                                <NavBar user={user}/>
                                {children}
                            </body>
                        </html>
                    </TimeProvider>
                </LevelProvider>
            </NumberQuestionProvider>
        </QuestionProvider>

    );
}
