import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./NavBar";
import { ClerkProvider } from "@clerk/nextjs";
import { LevelProvider } from "./context/levelContext";
import { QuestionProvider } from "@/app/context/questionContext";
import { NumberQuestionProvider } from "./context/numberQuestionsContext";
import { TimeProvider } from "./context/timeContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Ear Trainer",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkProvider>
            <QuestionProvider>
                <NumberQuestionProvider>
                    <LevelProvider>
                        <TimeProvider>
                            <html lang="en">
                                <body className={inter.className}>
                                    <NavBar />
                                    {children}
                                </body>
                            </html>
                        </TimeProvider>
                    </LevelProvider>
                </NumberQuestionProvider>
            </QuestionProvider>
        </ClerkProvider >

    );
}
